[package]
name = "q-expression"
description = "Metadata Plane: expression AST and shape algebra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
q-source = { workspace = true }
serde = { workspace = true }
q-nsir = { workspace = true }
