//! Data plane: **Tensor Tile Plane**, reading from the **Artifact Plane**
//! (ARCHITECTURE.md §2.1, §4.1, §9.3).
//!
//! `TILE-009` — the streaming block reader against **real SafeTensors bytes**,
//! read through the `mmap`-backed [`q_source::LocalFsSource`].
//!
//! # Where the expected values come from
//!
//! `fixtures/tiny-llama-2shard/golden.json`, generated by
//! `fixtures/generate_fixtures.py` and read back with the **official Python
//! `safetensors==0.8.0`** library. Nothing asserted here was produced by the
//! code under test, and no test in this file touches the network.
//!
//! The bf16 expectations are hand-computed from the bit patterns the golden
//! file records, because `golden.json` carries only the first `u16` of each bf16
//! tensor — numpy has no native bfloat16, so the generator could not emit a full
//! reference slice. That limit is stated rather than papered over.
//!
//! # `models/` is gitignored
//!
//! The real 337 MiB checkpoint is not committed and is not shared between git
//! worktrees, so the tests that want it **skip cleanly** when it is absent and
//! say so on stderr. Everything about it that can be asserted from the committed
//! `fixtures/real-checkpoint-record.json` is asserted unconditionally.

use q_safetensors::ingest::ingest_local;
use q_source::error::QError;
use q_source::role::TensorRole;
use q_source::{DType, LocalFsSource, ModelId, TensorDescriptor, TensorId};
use q_tensor_runtime::stream::{BlockStream, BlockStreamConfig};
use std::path::{Path, PathBuf};

const Q_PROJ: &str = "model.layers.10.self_attn.q_proj.weight";
const K_PROJ: &str = "model.layers.10.self_attn.k_proj.weight";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

fn fixture_dir() -> PathBuf {
    repo_root()
        .join("fixtures/tiny-llama-2shard")
        .canonicalize()
        .expect("fixtures/tiny-llama-2shard must exist; run fixtures/generate_fixtures.py")
}

fn golden() -> serde_json::Value {
    let path = fixture_dir().join("golden.json");
    let text = std::fs::read_to_string(&path).expect("golden.json");
    serde_json::from_str(&text).expect("golden.json parses")
}

fn golden_slice(tensor: &str) -> serde_json::Value {
    golden()["slices"]
        .as_array()
        .expect("slices")
        .iter()
        .find(|s| s["tensor"] == tensor)
        .cloned()
        .unwrap_or_else(|| panic!("golden.json has no slice for {tensor}"))
}

fn bits_of(value: &serde_json::Value) -> u32 {
    let hex = value.as_str().expect("bit pattern string");
    u32::from_str_radix(hex.trim_start_matches("0x"), 16).expect("hex bit pattern")
}

fn descriptor_of(raw_name: &str) -> TensorDescriptor {
    let outcome = ingest_local(fixture_dir()).expect("ingest the fixture");
    outcome
        .find(raw_name)
        .unwrap_or_else(|| panic!("{raw_name} is not in the fixture"))
        .clone()
}

// --- exact values against the Python reference -------------------------------

#[test]
fn a_block_of_the_real_fixture_decodes_to_the_python_safetensors_reference() {
    // golden.json records rows 100..104 x columns 40..44 of a [128, 48] tensor.
    // With 4x4 blocks the grid is 32 x 12, so that window is exactly block
    // 25 * 12 + 10 = 310. The block boundary is derived from the golden file's
    // own coordinates, not chosen to match an implementation.
    let slice = golden_slice(Q_PROJ);
    let rows = slice["rows"].as_array().unwrap();
    let columns = slice["columns"].as_array().unwrap();
    let (row_start, row_end) = (rows[0].as_u64().unwrap(), rows[1].as_u64().unwrap());
    let (column_start, column_end) = (columns[0].as_u64().unwrap(), columns[1].as_u64().unwrap());
    let block_rows = row_end - row_start;
    let block_columns = column_end - column_start;

    let d = descriptor_of(Q_PROJ);
    assert_eq!(d.shape, vec![128, 48]);
    assert_eq!(d.dtype, DType::F32);

    let source = LocalFsSource::open(fixture_dir()).unwrap();
    let mut stream = BlockStream::new(
        &source,
        d.clone(),
        BlockStreamConfig::default().with_block(block_rows, block_columns),
    )
    .unwrap();
    assert_eq!(stream.grid().grid_rows, 128 / block_rows);
    assert_eq!(stream.grid().grid_columns, 48 / block_columns);

    let index =
        (row_start / block_rows) * stream.grid().grid_columns + (column_start / block_columns);
    assert_eq!(index, 310);

    let block = stream
        .by_ref()
        .nth(index as usize)
        .expect("block 310")
        .expect("block reads");
    assert_eq!(block.extent.row_start, row_start);
    assert_eq!(block.extent.column_start, column_start);
    assert_eq!(block.bytes_read, block_rows * block_columns * 4);

    let expected = slice["values_f32_bits"].as_array().unwrap();
    assert_eq!(expected.len() as u64, block_rows * block_columns);
    for (i, want) in expected.iter().enumerate() {
        let r = i as u64 / block_columns;
        let c = i as u64 % block_columns;
        let got = block.data.get(r as usize, c as usize).unwrap();
        assert_eq!(
            got.to_bits(),
            bits_of(want),
            "element [{r},{c}] of block {} disagrees with golden.json",
            block.block_id
        );
    }

    // The scalar golden.json names separately, Q[10][100,42], is this block's
    // element [0, 2]. Asserting it through both records is the cross-check that
    // the block was placed at the right offset, not merely decoded correctly.
    let scalar = golden()["scalars"]
        .as_array()
        .unwrap()
        .iter()
        .find(|s| s["tensor"] == Q_PROJ && s["index"] == serde_json::json!([100, 42]))
        .cloned()
        .expect("Q[10][100,42] in golden.json");
    assert_eq!(
        block.data.get(0, 2).unwrap().to_bits(),
        bits_of(&scalar["value_f32_bits"])
    );
    assert_eq!(
        block.data.get(0, 2).unwrap() as f64,
        scalar["value_approx"].as_f64().unwrap()
    );
}

#[test]
fn a_second_golden_slice_decodes_at_the_origin_of_its_grid() {
    let slice = golden_slice(K_PROJ);
    let block_rows = slice["rows"][1].as_u64().unwrap() - slice["rows"][0].as_u64().unwrap();
    let block_columns =
        slice["columns"][1].as_u64().unwrap() - slice["columns"][0].as_u64().unwrap();
    assert_eq!((block_rows, block_columns), (2, 3));

    let source = LocalFsSource::open(fixture_dir()).unwrap();
    let mut stream = BlockStream::new(
        &source,
        descriptor_of(K_PROJ),
        BlockStreamConfig::default().with_block(block_rows, block_columns),
    )
    .unwrap();
    let block = stream.next().expect("first block").expect("reads");
    let expected = slice["values_f32_bits"].as_array().unwrap();
    let got: Vec<u32> = block.data.values.iter().map(|v| v.to_bits()).collect();
    let want: Vec<u32> = expected.iter().map(bits_of).collect();
    assert_eq!(got, want);
    assert_eq!(block.bytes_read, 2 * 3 * 4);
}

#[test]
fn a_bf16_tensor_streams_to_hand_computed_values_rather_than_rounded_ones() {
    // golden.json records only the first u16 of each bf16 tensor, because numpy
    // has no native bfloat16 and the generator could not emit a reference slice.
    // bf16 *is* the high half of an f32, so the expected f32 bit pattern is the
    // recorded u16 shifted left 16 — derived from the format, by hand.
    //
    //   0x3D1E -> f32 0x3D1E0000: exponent 0x7A = 122 -> 2^-5,
    //             mantissa 0x1E0000 / 2^23 = 0.234375
    //             value = 1.234375 * 2^-5 = 0.03857421875
    for entry in golden()["bf16"].as_array().expect("bf16 section") {
        let raw_name = entry["tensor"].as_str().unwrap();
        let first = bits_of(&entry["first_u16_le"]) as u16;
        let d = descriptor_of(raw_name);
        assert_eq!(d.dtype, DType::BF16);
        assert_eq!(d.shape, vec![64, 48]);
        assert_eq!(d.byte_length(), entry["byte_length"].as_u64().unwrap());

        let source = LocalFsSource::open(fixture_dir()).unwrap();
        let mut stream = BlockStream::new(
            &source,
            d.clone(),
            BlockStreamConfig::default().with_block(8, 8),
        )
        .unwrap();
        let block = stream.next().expect("first block").expect("reads");
        let got = block.data.get(0, 0).unwrap();
        assert_eq!(
            got.to_bits(),
            (first as u32) << 16,
            "{raw_name}: bf16 0x{first:04X} must widen to f32 0x{:08X}",
            (first as u32) << 16
        );
        // Two bytes per element, not four: the storage width, not the decoded
        // one, is what was read.
        assert_eq!(block.bytes_read, 8 * 8 * 2);

        // Compared as f64 so the *exact* hand-computed value can be written out.
        // `f32 as f64` is lossless, and 0.03857421875 is not an f32 literal
        // rustc will accept without complaining about precision it cannot hold —
        // yet it is the exact value, so truncating the literal would hide the
        // derivation rather than simplify it.
        if first == 0x3D1E {
            assert_eq!(got as f64, 0.038_574_218_75_f64, "hand-computed value");
        }
        if first == 0x3925 {
            // 0x39250000: exponent field 114 -> 2^-13, mantissa 2424832 / 2^23
            // = 0.2890625; value = 1.2890625 * 2^-13.
            //
            // Cross-checked with Python `struct.unpack('<f', struct.pack('<I',
            // 0x39250000))`, which is how the wrong literal that was here first
            // — 0.0001573486328125, an arithmetic slip on the same derivation —
            // was caught. The check earned its place.
            assert_eq!(
                got as f64, 0.000_157_356_262_207_031_25_f64,
                "hand-computed value"
            );
        }
    }
}

#[test]
fn streaming_the_whole_real_tensor_reads_its_payload_exactly_once() {
    let d = descriptor_of(Q_PROJ);
    let payload = d.byte_length();
    assert_eq!(payload, 128 * 48 * 4);

    let source = LocalFsSource::open(fixture_dir()).unwrap();
    // The default 256x256 block is larger than this [128, 48] tensor, so the
    // single block clamps to 128x48 — clamped, not padded.
    let mut stream = BlockStream::new(&source, d, BlockStreamConfig::default()).unwrap();
    assert_eq!(stream.block_count(), 1);
    let outcome = stream
        .drive(|block| {
            assert_eq!((block.data.rows, block.data.columns), (128, 48));
            assert_eq!(block.data.values.len(), 128 * 48);
            Ok(())
        })
        .unwrap();
    assert_eq!(outcome.bytes_read, payload);
    assert!(outcome.is_complete());

    // With 16x16 blocks the same payload is read in 8 x 3 = 24 blocks, and the
    // total is identical: no block is read twice and none is skipped.
    let d = descriptor_of(Q_PROJ);
    let mut stream =
        BlockStream::new(&source, d, BlockStreamConfig::default().with_block(16, 16)).unwrap();
    assert_eq!(stream.block_count(), 8 * 3);
    let outcome = stream.drive(|_| Ok(())).unwrap();
    assert_eq!(outcome.bytes_read, payload);
    assert_eq!(outcome.blocks_emitted, 24);
}

// --- negative paths against real files ---------------------------------------

#[test]
fn a_missing_shard_is_refused_by_name_rather_than_read_as_zeros() {
    let mut d = descriptor_of(Q_PROJ);
    d.shard_uri = "model-00099-of-00002.safetensors".into();
    let source = LocalFsSource::open(fixture_dir()).unwrap();
    let mut stream =
        BlockStream::new(&source, d, BlockStreamConfig::default().with_block(16, 16)).unwrap();
    let err = stream.next().expect("an attempt").unwrap_err();
    match &err {
        QError::NotFound(detail) => assert!(
            detail.contains("model-00099-of-00002.safetensors"),
            "message was {detail}"
        ),
        other => panic!("expected NotFound, got {other:?}"),
    }
    assert_eq!(stream.blocks_emitted(), 0);
    assert!(stream.next().is_none(), "a failed block is never skipped");
}

#[test]
fn a_truncated_copy_of_a_real_shard_is_refused_with_the_offending_byte_range() {
    // The fixture is copied, never modified in place.
    let dir = tempfile::tempdir().unwrap();
    let shard = "model-00002-of-00002.safetensors";
    let original = fixture_dir().join(shard);
    let bytes = std::fs::read(&original).unwrap();

    let d = descriptor_of(Q_PROJ);
    assert_eq!(d.shard_uri, shard, "Q[10] must live in the second shard");
    // Cut five rows into the tensor, so the very first 16-row block overruns the
    // file. A truncation that landed after the tensor would prove nothing.
    let keep = (d.byte_start + 5 * 48 * 4) as usize;
    assert!(keep < bytes.len() && (keep as u64) < d.byte_end);
    std::fs::write(dir.path().join(shard), &bytes[..keep]).unwrap();
    std::fs::copy(
        fixture_dir().join("config.json"),
        dir.path().join("config.json"),
    )
    .unwrap();

    let source = LocalFsSource::open(dir.path()).unwrap();
    let mut stream =
        BlockStream::new(&source, d, BlockStreamConfig::default().with_block(16, 16)).unwrap();
    let mut err = None;
    for item in stream.by_ref() {
        if let Err(e) = item {
            err = Some(e);
            break;
        }
    }
    let err = err.expect("the truncated shard must be refused");
    match &err {
        QError::RangeOutOfBounds {
            uri,
            start,
            end,
            length,
        } => {
            assert_eq!(uri, shard);
            assert_eq!(
                *length, keep as u64,
                "the refusal reports the real file length"
            );
            assert!(*end > *length, "the refused range overran the file");
            assert!(*start < *end);
        }
        other => panic!("expected RangeOutOfBounds, got {other:?}"),
    }
    // The original is untouched.
    assert_eq!(
        std::fs::metadata(&original).unwrap().len(),
        bytes.len() as u64
    );
}

// --- the real checkpoint ------------------------------------------------------

fn real_checkpoint_record() -> serde_json::Value {
    let path = repo_root().join("fixtures/real-checkpoint-record.json");
    let text = std::fs::read_to_string(&path).expect("fixtures/real-checkpoint-record.json");
    serde_json::from_str(&text).expect("the record parses")
}

/// Runs with or without `models/`: the record is committed, the weights are not.
#[test]
fn the_real_checkpoints_rank_four_masks_are_refused_rather_than_flattened() {
    let record = real_checkpoint_record();
    let shape: Vec<u64> = record["rank4_shape"]
        .as_array()
        .expect("rank4_shape")
        .iter()
        .map(|v| v.as_u64().unwrap())
        .collect();
    assert_eq!(shape, vec![1, 1, 1024, 1024]);
    let names = record["rank4_tensor_names"].as_array().expect("names");
    assert_eq!(names.len(), 6);

    struct NeverRead;
    impl q_source::ModelSource for NeverRead {
        fn manifest(&self) -> q_source::error::Result<q_source::ModelManifest> {
            Err(QError::NotFound("not used".into()))
        }
        fn read_range(
            &self,
            _uri: &str,
            _offset: u64,
            _length: u64,
        ) -> q_source::error::Result<q_source::manifest::ByteStream> {
            panic!("a rank-4 refusal must happen before any read");
        }
    }

    let elements: u64 = shape.iter().product();
    for name in names {
        let raw_name = name.as_str().unwrap();
        let d = TensorDescriptor {
            tensor_id: TensorId::derive(
                ModelId::derive("local:distilbert-distilgpt2", "", ""),
                raw_name,
            ),
            raw_name: raw_name.into(),
            canonical_name: raw_name.into(),
            shape: shape.clone(),
            dtype: DType::F32,
            shard_uri: "model.safetensors".into(),
            byte_start: 8285,
            byte_end: 8285 + elements * 4,
            layer_index: None,
            semantic_role: TensorRole::Unknown,
        };
        let err = BlockStream::new(&NeverRead, d, BlockStreamConfig::default()).unwrap_err();
        assert_eq!(err.requirement_id(), Some("GRID-007"));
        let msg = err.to_string();
        assert!(msg.contains("rank 4"), "message was {msg}");
        assert!(
            msg.contains("refused rather than flattened"),
            "message was {msg}"
        );
    }
}

/// Skips cleanly when `models/` is absent, which is the normal state of a fresh
/// worktree — `models/` is gitignored and is not shared between worktrees.
#[test]
fn a_real_checkpoint_tensor_streams_reading_only_the_blocks_asked_for() {
    let dir = repo_root().join("models/distilbert-distilgpt2");
    let weights = dir.join("model.safetensors");
    if !weights.exists() {
        eprintln!(
            "SKIPPED a_real_checkpoint_tensor_streams_reading_only_the_blocks_asked_for: \
             {} is absent. models/ is gitignored, so this is expected on a fresh \
             worktree; fixtures/real-checkpoint-record.json carries what was measured.",
            weights.display()
        );
        return;
    }

    let record = real_checkpoint_record();
    let bytes_on_disk = record["bytes_on_disk"].as_u64().unwrap();
    assert_eq!(
        std::fs::metadata(&weights).unwrap().len(),
        bytes_on_disk,
        "the checkpoint on disk is not the one the record describes"
    );

    let outcome = ingest_local(&dir).expect("ingest the real checkpoint");
    assert_eq!(
        outcome.tensor_count() as u64,
        record["tensor_count"].as_u64().unwrap()
    );

    // The largest rank-2 tensor, chosen by size then name so the pick is
    // deterministic rather than incidental.
    let mut rank2: Vec<&TensorDescriptor> = outcome
        .descriptors
        .iter()
        .filter(|d| d.shape.len() == 2 && d.dtype == DType::F32)
        .collect();
    rank2.sort_by(|a, b| {
        b.byte_length()
            .cmp(&a.byte_length())
            .then(a.raw_name.cmp(&b.raw_name))
    });
    let d = (*rank2.first().expect("a rank-2 F32 tensor")).clone();

    let source = LocalFsSource::open(&dir).unwrap();
    let mut stream = BlockStream::new(&source, d.clone(), BlockStreamConfig::default()).unwrap();
    let grid = stream.grid();
    let total_blocks = stream.block_count();

    // Four blocks only. The point is that reading four blocks of a 337 MiB
    // checkpoint costs four blocks' worth of bytes, not the file.
    let mut bytes = 0u64;
    let mut taken = 0u64;
    for item in stream.by_ref().take(4) {
        let block = item.expect("block");
        assert_eq!(block.bytes_read, block.extent.element_count() * 4);
        bytes += block.bytes_read;
        taken += 1;
    }
    assert_eq!(taken, 4.min(total_blocks));
    assert!(
        bytes <= 4 * 256 * 256 * 4,
        "four 256x256 f32 blocks is at most 1 MiB; read {bytes}"
    );
    let fraction = bytes as f64 / bytes_on_disk as f64 * 100.0;
    assert!(
        fraction < 1.0,
        "reading four blocks touched {fraction:.4} % of the checkpoint"
    );

    eprintln!(
        "TILE-009 on the real checkpoint (exact): tensor {} {:?} F32, grid {}x{} = {} blocks; \
         4 blocks read {} bytes = {:.6} % of the {} byte file",
        d.raw_name,
        d.shape,
        grid.grid_rows,
        grid.grid_columns,
        total_blocks,
        bytes,
        fraction,
        bytes_on_disk,
    );
}
